name: Build All Platforms

on:
  workflow_dispatch:

jobs:
  android:
    name: Trigger Android Build
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  windows:
    name: Trigger Windows Build
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  linux:
    name: Trigger Linux Build
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
